name: kavli
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - h5py
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - seaborn
  - tqdm
  - pip:
      - ipywidgets==8.0.6
      - jupyterlab-widgets==3.0.7
      - tomso==0.2.1
